---
title: "GCR_model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load all the packages
```{r}
library(tidymodels)

library(DALEX)
library(DALEXtra)

library(fairmodels)

library(yardstick)

```


# load dataset
```{r}
# iets bedenken zodat na gebruikt kan worden en geen errors geeft!
GCR <- read.csv('german_credit_data.csv',
                header = TRUE)

GCR <- na.omit(GCR)     #niet gebruiken voor optimale accuracy
GCR <- GCR %>% select(-X)
GCR$Job <- if_else(GCR$Job == 0, "unskilled and non-resident",
                   if_else(GCR$Job == 1, "unskilled and resident",
                           if_else(GCR$Job == 2, "skilled", "highly skilled")))
GCR$Risk <- if_else(GCR$Risk == 'good', 1, 0)

GCR$Risk <- as.factor(GCR$Risk)

set.seed(123)
GCR_split <- initial_split(GCR, strata = Risk)
GCR_train <- training(GCR_split)
GCR_test <- testing(GCR_split)
```

```{r}
tidy_kfolds <- vfold_cv(GCR_train)


xg_rec <- recipe(Risk~., data = GCR_train) %>%
  step_impute_knn(Saving.accounts,  Checking.account) %>%  
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_impute_median(all_predictors()) %>% 
  step_normalize(all_predictors())
```

```{r}
tidy_boosted_model <- boost_tree(trees = tune(),
                                 min_n = tune(),
                                 learn_rate = tune()) %>% 
  set_mode("classification") %>% 
  set_engine("xgboost")

tidy_knn_model <- nearest_neighbor(neighbors = tune()) %>% 
  set_mode("classification") %>% 
  set_engine("kknn")

boosted_grid <- grid_regular(parameters(tidy_boosted_model), levels = 5)
knn_grid <- grid_regular(parameters(tidy_knn_model), levels = 10)

```


```{r}
# Dials pacakge 
boosted_grid <- grid_regular(parameters(tidy_boosted_model), levels = 5)
knn_grid <- grid_regular(parameters(tidy_knn_model), levels = 10)
```


```{r}
# Tune pacakge 
boosted_tune <- tune_grid(tidy_boosted_model,
                          xg_rec,
                          resamples = tidy_kfolds,
                          grid = boosted_grid)

knn_tune <- tune_grid(tidy_knn_model,
                      xg_rec,
                      resamples = tidy_kfolds,
                      grid = knn_grid)
```


```{r}
# getting best params
boosted_param <- boosted_tune %>% select_best("roc_auc")
knn_param <- knn_tune %>% select_best("roc_auc")

```



```{r}
# finalizing
tidy_boosted_model <- finalize_model(tidy_boosted_model, boosted_param)
tidy_knn_model <- finalize_model(tidy_knn_model, knn_param)



boosted_wf <- workflow() %>% 
  add_model(tidy_boosted_model) %>% 
  add_recipe(xg_rec)

knn_wf <- workflow() %>% 
  add_model(tidy_knn_model) %>% 
  add_recipe(xg_rec)


boosted_res <- last_fit(boosted_wf, GCR_split)
knn_res <- last_fit(knn_wf, GCR_split)


bind_rows(
  boosted_res %>% mutate(model = "xgb"),
  knn_res %>% mutate(model = "knn")
) %>% 
  unnest(.metrics)
boosted_res %>% unnest(.predictions) %>% 
  conf_mat(truth = Risk, estimate = .pred_class)
```





```{r}
# Fit the entire data set using the final wf 
final_boosted_model <- fit(boosted_wf, GCR)
saveRDS(final_boosted_model, "GCR_xgmodel.rds")
```

```{r}
custom_model_expl <- function(recipe_workflow) {return(recipe_workflow$fit$fit)}

custom_data_expl <- function(recipe_workflow, dataset, target_variable) { 
  data_return <- as.data.frame(prep(recipe_workflow$pre$actions$recipe$recipe, dataset) %>% 
                                 bake(dataset) %>% 
                                 select(-target_variable))
  
  return(data_return)
}

custom_y_expl <- function(recipe_workflow, dataset, target_variable) { 
  data_return <- prep(recipe_workflow$pre$actions$recipe$recipe, dataset) %>% 
    bake(dataset) %>% 
    mutate(target_variable = ifelse(target_variable == 'good', 1, 0))  %>% 
    pull(target_variable)
  
  return(data_return)
}

```




```{r}
# explainer
explainer <- DALEX::explain(
  model = custom_model_expl(final_boosted_model),
  data = custom_data_expl(final_boosted_model, GCR_train,  "Risk"),
  y = custom_y_expl(final_boosted_model, GCR_train,  "Risk"),
  label = "XGboost")
```

```{r}

saveRDS(explainer, "GCR_xg_explainer.rds")

saveRDS(xg_rec, "GCR_xg_rec.rds")
```

